language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

services:
  - postgres

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database travisci_;' -U postgres

install:
  - composer install

after_script:
  - vendor/bin/test-reporter --coverage-report=tests/log/coverage.xml
